### ISSUE TITLE
timestream-write: add support for customer-defined partition keys

### ISSUE THREAD

**Issue by sannaroby** [upbound/provider-aws#1006]
### What problem are you facing?
In June 2023, aws introduced in timestream the support for customer-defined partition keys.
aws blog post: https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-timestream-customer-defined-partition-keys/
aws documentation: https://docs.aws.amazon.com/timestream/latest/developerguide/customer-defined-partition-keys-getting-started.html
terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_table#customer-defined-partition-key

### How could Official AWS Provider help solve your problem?
Implement proper support for timestream customer-defined partition keys.

**Comment by mbbush** [comment]
Looking at the terraform provider docs, this property isn't present in terraform-provider-aws version 4.67.0, which is what this provider currently uses. There are some breaking changes in version 5.0, that we are planning on upgrading to, although the details are still being worked out by some of the upbound folks. 

Since this is just a schema change, we should get this "for free" once we're using the latest version of the terraform provider.

**Comment by turkenf** [comment]
Currently [available](https://github.com/upbound/provider-aws/blob/b4bbf97eeb0e242d168d9b2d5c9ddaa2fe697e73/apis/timestreamwrite/v1beta1/zz_table_types.go#L44) in the main branch, you will be able to use it next release. So I'm closing this issue, feel free to open it again if you encounter any problems.
