### ISSUE TITLE
[Elasticache] - Support enabling Encryption in transit on existing clusters

### ISSUE THREAD

**Issue by dhumphries-sainsburys** [upbound/provider-aws#1103]
### What problem are you facing?

Redis 7.0 onwards supports enabling encryption in transit on an existing cluster or replication group but this doesn't seem to be allowed in the provider with the below:

```
        async update failed: refuse to update the external resource: cannot
        change the value of the argument "transit_encryption_enabled" from
        "false" to "true"
```

[[1]](https://docs.aws.amazon.com/cli/latest/reference/elasticache/modify-replication-group.html)
[[2]](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption-enable.html)

### How could Official AWS Provider help solve your problem?
Support the ability to switch between encrypted transit being false to true

**Comment by turkenf** [comment]
Hi @dhumphries-sainsburys, 

Changing this field requires deleting and recreating the existing resource due to the behavior of the underlying provider.
- [transit_encryption_enabled](https://github.com/hashicorp/terraform-provider-aws/blob/697c29e95d8d0795d337a3898e6f965f99df6186/internal/service/elasticache/cluster.go#L331) for Cluster resource
- [transit_encryption_enabled](https://github.com/hashicorp/terraform-provider-aws/blob/697c29e95d8d0795d337a3898e6f965f99df6186/internal/service/elasticache/replication_group.go#L330) for ReplicationGroup resource

According to the [Crossplane Resource Model](https://docs.crossplane.io/latest/concepts/managed-resources/#immutable-fields), this is something we do not allow.

**Comment by turkenf** [comment]
Since this is to be expected, I am closing this issue. Upstream [issue](https://github.com/crossplane/upjet/issues/78) with rejecting change requests for immutable fields.
