### ISSUE TITLE
Moving ram (4) resources to v1beta1 version

### ISSUE THREAD

**Issue by ulucinar** [upbound/provider-aws#253]
Moving 4 resources in the `ram` group:
- [x] [`aws_ram_principal_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_principal_association)
- [x] [`aws_ram_resource_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_association)
- [x] [`aws_ram_resource_share`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_share)
- [x] [`aws_ram_resource_share_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_share_accepter)

**Comment by sterziev88** [comment]
Hi team,

Is there any progress with that ticket? Because I have not been able to find a way to send invitations to multiple accounts within the same organization, nor have I found a way to accept invitations using Crossplane. While there is one CRD available for creating a resource share, it does not provide an option to specify which accounts to invite.
