### ISSUE TITLE
Moving iot (1) resource to v1beta1 version

### ISSUE THREAD

**Issue by steperchuk** [upbound/provider-aws#361]
External name configuration of 1 resource in the `iot` group:
- [ ] [`aws_iot_topic_rule_destination`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule_destination)

**Comment by blakebarnett** [comment]
Could this be added with documentation for the resource that explains the `deletionPolicy` should be `Orphan` due to this behavior?

**Comment by mbbush** [comment]
Terraform suffers from the [same issue](https://github.com/hashicorp/terraform-provider-aws/issues/26567). Making matters worse, Terraform doesn't expose the ids of the created ENIs, although there's a [feature request](https://github.com/hashicorp/terraform-provider-aws/issues/26568) for it.

**Comment by mbbush** [comment]
I think the underlying issue here is a race condition during delete. In order to delete this cleanly, you have to delay deleting the IAM role that `iot.amazonaws.com` assumes, and which has permission to delete network interfaces, until after the network interfaces have been successfully deleted. 

One part I'm not sure about is whether it is safe to delete the role as soon as the topic rule destination delete has completed. In the terraform e2e tests, they wait until everything has been deleted (including the VPC) before deleting the role. 

I'm struggling to come up with a good way to encode the concept of "this resource must not be deleted until that resource has been deleted first" in the crossplane resource model. Anybody have any ideas?
