### ISSUE TITLE
CI/lint job fails very often with the timeout error

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/provider-aws#573]
`CI/lint` job in this repo fails very often with the timeout error. While lint works successfully locally, there are problems in PRs due to this timeout error in GitHub. 

We can increase the timeout of this job or we may consider researching another machine to run the GitHub actions.

**Comment by dverveiko** [comment]
@sergenyalcin PR with temporary workaround - https://github.com/upbound/uptest/pull/81

cc @ulucinar

**Comment by muvaf** [comment]
I think we started running into this problem once we generated hundreds of CRDs because the amount of code golangci-lint needs to analyze increases with the number of CRDs. The generated files are excluded by default but that exclusion doesn't mean they are not analyzed, just that their issues are not reported and that's because without them, human-written code would give compile errors. Given that we can't really reduce the amount of code that's analyzed, I dug into the caching mechanisms to make it more efficient.

Reading the [caching internals](https://github.com/golangci/golangci-lint-action#caching-internals) of golangci-lint, it includes the hash of `go.mod` file in its cache key, which means we probably see this issue more often when we make a change in that file or every 7 days, which is the default invalidation period. Reading the logs of my PR [here](https://github.com/upbound/provider-aws/actions/runs/4537857127/jobs/8016603215?pr=628), it calculates two keys with `2777` as the week number. The full key doesn't match since it includes the hash of `go.mod` file and I have a change there but the second key matches [an entry](https://github.com/upbound/provider-aws/actions/caches) in our current GH cache partially since it doesn't have the hash. However, the cache originated from the branch `release-0.32` and according to [the docs of GH](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), only branches originated from that branch can access that cache, i.e. neither `main` nor any PR branches.

I think what happens is that every time `lint` runs in a PR or release branch, it passes quickly if the cache record originated from `main` branch since the cache hit probability is high (right now there is a single entry that came from `release-0.32` branch and its size is 2.4GB). However, if a cache from a release or PR branch makes it, then it just occupies space and increases the odds of the cache miss. My proposal is that we should restrict adding cache entry only to runs in `main` branch in order to reduce the possibility of cache misses given that there is an upper limit to how much cache you can hold and how long you can keep it.

**Comment by muvaf** [comment]
FWIW, the default Github runner is just a 2-core VM. The linter has the default of 8-core parallelization and completes in about 2m21s in my machine. So, increasing the number of cores of the runners would likely help a lot. But looks like it [needs to be enabled](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners) by the admin of Upbound org to be able to request from workflow file. cc @jeanduplessis 

I think we should do both of the following:
* Limit caching of `golangci/golangci-lint-action@v3` to `main` with an argument.
* Use 8-cores VMs for `lint` jobs.

**Comment by jeanduplessis** [comment]
I've opened a request with the platform team to provide more powerful runners: https://github.com/upbound/platform-core/issues/841

**Comment by dverveiko** [comment]
Powerful runners was provided. Issue resolved.
