### ISSUE TITLE
ECS Service cluster fields not working as documented

### ISSUE THREAD

**Issue by martinflemingdev** [upbound/provider-aws#624]
### What happened?

![ecs-service-doc](https://user-images.githubusercontent.com/78125388/227317181-66a21c9a-ca20-4502-8938-6d366ca4cded.png)

spec.forProvider.**cluster**, spec.forProvider.**clusterSelector** , spec.forProvider.**clusterRef**  fields do not work as expected, documentation says they take an ARN, but only the cluster name works.

![ecs-service-error](https://user-images.githubusercontent.com/78125388/227320628-e91a51f7-b963-46c2-be9d-33e2c9e27714.png)

When ARN is given, error message is : "observe failed: cannot run refresh: refresh failed: reading ECS service (arn:aws:ecs:us-east-1:011882408883:cluster/sample-app-cluster/sample-app-service): InvalidParameterException: Unsupported resource type: cluster:"

Therefore **clusterSelector** and **clusterRef** fields that resolve to ARN are also broken and throw the same error as above.

Workaround at this time is to hardcode the cluster name into the spec.forProvider.cluster field

![ecs-service-works](https://user-images.githubusercontent.com/78125388/227319660-80a8108a-97b4-4b18-91ef-793df5ef98fc.png)

### How can we reproduce it?

Install newest Upbound AWS provider and apply manifests here:
https://github.com/martinflemingdev/upbound-ECS-service-cluster-field-bug

### What environment did it happen in?

Upbound AWS Provider: [upbound/provider-aws@v0.31.0](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.31.0)

**Comment by haarchri** [comment]
@dverveiko  the problem is that the description tells you to use ARN instead of clusterName/short-id only 
https://marketplace.upbound.io/providers/upbound/provider-aws/v0.32.0/resources/ecs.aws.upbound.io/Service/v1beta1#doc:spec-forProvider-cluster

`ARN of an ECS cluster.` so i would say to update the description
added a fix for the description in https://github.com/upbound/provider-aws/pull/643
