### ISSUE TITLE
Add EKS version to status 

### ISSUE THREAD

**Issue by clementblaise** [upbound/provider-aws#676]
### What problem are you facing?

Currently, only the platform_version is outputted. The Kubernetes version number would be helpful to act as the observed version of the Cluster to patch the NodeGroup accordingly. Without it, we need to rely on the version passed from the Claim but changing this value results in the cluster and the node pool being upgraded simultaneously, which makes the node pool fail because the control plane is not yet updated.

### How could Official AWS Provider help solve your problem?

The version is defined on `ClusterObservation` but for some reason is not defined on the CRD

https://github.com/upbound/provider-aws/blob/081290dd63225cb443511fe20a9e909994459d7b/apis/eks/v1beta1/zz_cluster_types.go#L79

https://github.com/upbound/provider-aws/blob/081290dd63225cb443511fe20a9e909994459d7b/package/crds/eks.aws.upbound.io_clusters.yaml#L679

**Comment by svscheg** [comment]
Hi @clementblaise !

[version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#version) is normally a Terraform argument, i.e., it’s available under spec.forProvider in the generated MR (Cluster.eks). But with the introduction of the observe-only resources, we now report most Terraform arguments also under status.atProvider (so that clients can observe the values of these arguments from status).

The version field is available under status.atProvider (due to the observe-only changes). The generated CRD have that field in its schema: https://github.com/upbound/provider-aws/blob/081290dd63225cb443511fe20a9e909994459d7b/package/crds/eks.aws.upbound.io_clusters.yaml#L868

Actually the generated CRD schema has status.atProvider.version.
This is a new change that we introduced with the support for observe-only resources (the ObserveOnly management policy, here we can reference the relevant design doc: https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#proposal).

So need to clarify did you specify a version at spec.forProvider explicitly? version is [optional](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#version), and if not specified the latest available version is used. If you don’t specify a version at spec.forProvider then it’s expected because [we do not late-initialize after an import](https://github.com/upbound/upjet/blob/1268a48eba95ef194823f4bcc118e14a5d867a94/pkg/controller/external.go#L376).

**Comment by clementblaise** [comment]
@svscheg Thank you for the response. I am not talking about the version set in `spec.forProvider` but the actual version of the cluster which shows up in the AWS Console. 

The reason is that when you do an update, the `spec.forProvider` version it will differ for a short time from the actual one or be observed while the control plane is upgrading.

**Comment by svscheg** [comment]
Hi @clementblaise !
Seems we speak about the same `status.atProvider.version` attribute, so let me add more information about it:

1. The generated CRD schema has `status.atProvider.version`
https://github.com/upbound/provider-aws/blob/081290dd63225cb443511fe20a9e909994459d7b/package/crds/eks.aws.upbound.io_clusters.yaml#L868 (as I can see it is the same attribute `status.atProvider.version` - https://github.com/crossplane-contrib/provider-aws/blob/d45413992bf1d949751593d5ace3a0e015bc9ad7/package/crds/eks.aws.crossplane.io_clusters.yaml#L816-L819)
this is a new change that we introduced with the support for observe-only resources - https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#proposal

2. If we do not specify a version at `spec.forProvider`  version field will not  be available under status.atProvider and it’s expected because [we do not late-initialize after an import](https://github.com/upbound/upjet/blob/1268a48eba95ef194823f4bcc118e14a5d867a94/pkg/controller/external.go#L376). Late-initialization is the setting of previously unset spec fields from the observed values of the external resource. For example, even if you don’t specify spec.forProvider.version, the cloud provider (AWS) determines the latest available Kubernetes API version and sets it, and with late-initialization, upjet sets the uninitialized spec.forProvider.version to the value observed from the external resource. But this is currently not done for status.atProvider (late-initialization is conventionally for spec fields, [here’s a reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#controller-assigned-defaults-aka-late-initialization) from the Kubernetes API conventions.).

**We may also propose a workaround** - patching from `spec.forProvider.version` instead of `status.atProvider.version`. Could you please try it and let me know if I am wrong and it can't help you?

**Comment by clementblaise** [comment]
I recently updated the provider to `v.0.35.0`, which now shows the accurate observed version for `status.atProvider.version`. I could also use the `versionRef`, which didn't work previously.

**Comment by jbw976** [comment]
Thanks a lot for confirming this @clementblaise!! 🙇‍♂️
