### ISSUE TITLE
securityGroupIdSelector missing in clusters.elasticache.aws.upbound.io

### ISSUE THREAD

**Issue by alexinthesky** [upbound/provider-aws#698]
### What problem are you facing?

the clusters.elasticache.aws.upbound.io CRD does not provide **securityGroupIdRefs / securityGroupIdSelector** but only a **securityGroupIds**

### How could Official AWS Provider help solve your problem?
explain why these are not present ( and yet they are available for the [replicationgroups.elasticache.aws.upbound.io](https://github.com/upbound/provider-aws/blob/main/package/crds/elasticache.aws.upbound.io_replicationgroups.yaml#L348) )

https://github.com/upbound/provider-aws/pull/679 fixes this but I need to understand why the extra code is need for the cluster and not the replicationgroups !

**Comment by turkenf** [comment]
Hi @alexinthesky,

Thank you for raising this issue. We generate these parameters by looking at the terraform documentation. I reviewed the terraform documents but I couldn't understand why it was generated for `ReplicationGroup.elasticache` and not for `Cluster.elasticache`. @ulucinar, @sergenyalcin do you have any idea?

**Comment by ulucinar** [comment]
Hi @turkenf & @alexinthesky,
It turns out that we are replacing the `config.Resource.References` map instead of adding new items on top of the automatically injected references:
https://github.com/upbound/provider-aws/blob/a4a4954af724392fbfc0acd4993cfa439641b22f/config/elasticache/config.go#L14

Opened #708 to fix this. Thank you!
